logging:
  file:
    name: F:/LogFiles/employee-details.log
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/aop_db
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
springdoc:
  api-docs:
    path: /api-doc
employee-app:
  messages:
    emp-not-found: "Employee Not Found With Id : %s"
    emp-deletion-success: "Employee Deleted Successfully With Id : "    